#!/bin/sh
# $Id: dvk_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="dvk"
device="dvk"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's dvk that has several devices in it.

rm -f /dev/dvs
mknod /dev/dvs c $major 0
ln -sf ${device} /dev/${device}
chgrp $group /dev/${device}
chmod $mode  /dev/${device}





