#ifndef _COM_DVS_ERRNO_H
#define _COM_DVS_ERRNO_H

#define _SIGN         -

/* Here are the numerical values of the error numbers. */
#define _NERROR               70  /* number of errors */  

#define EDVSGENERIC      (_SIGN 99)  /* generic error */
#define EDVSPERM         (_SIGN  1)  /* operation not permitted */
#define EDVSNOENT        (_SIGN  2)  /* no such file or directory */
#define EDVSSRCH         (_SIGN  3)  /* no such process */
#define EDVSINTR         (_SIGN  4)  /* interrupted function call */
#define EDVSIO           (_SIGN  5)  /* input/output error */
#define EDVSNXIO         (_SIGN  6)  /* no such device or address */
#define EDVS2BIG         (_SIGN  7)  /* arg list too long */
#define EDVSNOEXEC       (_SIGN  8)  /* exec format error */
#define EDVSBADF         (_SIGN  9)  /* bad file descriptor */
#define EDVSCHILD        (_SIGN 10)  /* no child process */
#define EDVSAGAIN        (_SIGN 11)  /* resource temporarily unavailable */
#define EDVSNOMEM        (_SIGN 12)  /* not enough space */
#define EDVSACCES        (_SIGN 13)  /* permission denied */
#define EDVSFAULT        (_SIGN 14)  /* bad address */
#define EDVSNOTBLK       (_SIGN 15)  /* Extension: not a block special file */
#define EDVSBUSY         (_SIGN 16)  /* resource busy */
#define EDVSEXIST        (_SIGN 17)  /* file exists */
#define EDVSXDEV         (_SIGN 18)  /* improper link */
#define EDVSNODEV        (_SIGN 19)  /* no such device */
#define EDVSNOTDIR       (_SIGN 20)  /* not a directory */
#define EDVSISDIR        (_SIGN 21)  /* is a directory */
#define EDVSINVAL        (_SIGN 22)  /* invalid argument */
#define EDVSNFILE        (_SIGN 23)  /* too many open files in system */
#define EDVSMFILE        (_SIGN 24)  /* too many open files */
#define EDVSNOTTY        (_SIGN 25)  /* inappropriate I/O control operation */
#define EDVSTXTBSY       (_SIGN 26)  /* no longer used */
#define EDVSFBIG         (_SIGN 27)  /* file too large */
#define EDVSNOSPC        (_SIGN 28)  /* no space left on device */
#define EDVSSPIPE        (_SIGN 29)  /* invalid seek */
#define EDVSROFS         (_SIGN 30)  /* read-only file system */
#define EDVSMLINK        (_SIGN 31)  /* too many links */
#define EDVSPIPE         (_SIGN 32)  /* broken pipe */
#define EDVSDOM          (_SIGN 33)  /* domain error    	(from ANSI C std) */
#define EDVSRANGE        (_SIGN 34)  /* result too large	(from ANSI C std) */
#define EDVSDEADLK       (_SIGN 35)  /* resource deadlock avoided */
#define EDVSNAMETOOLONG  (_SIGN 36)  /* file name too long */
#define EDVSNOLCK        (_SIGN 37)  /* no locks available */
#define EDVSNOSYS        (_SIGN 38)  /* function not implemented */
#define EDVSNOTEMPTY     (_SIGN 39)  /* directory not empty */
#define EDVSLOOP         (_SIGN 40)  /* too many levels of symlinks detected */

/* The following errors relate to networking. */
#define EDVSPACKSIZE     (_SIGN 50)  /* invalid packet size for some protocol */
#define EDVSOUTOFBUFS    (_SIGN 51)  /* not enough buffers left */
#define EDVSBADIOCTL     (_SIGN 52)  /* illegal ioctl for device */
#define EDVSBADMODE      (_SIGN 53)  /* badmode in ioctl */
#define EDVSWOULDBLOCK   (_SIGN 54)
#define EDVSBADDEST      (_SIGN 55)  /* not a valid destination address */
#define EDVSDSTNOTRCH    (_SIGN 56)  /* destination not reachable */
#define EDVSISCONN	      (_SIGN 57)  /* all ready connected */
#define EDVSADDRINUSE    (_SIGN 58)  /* address in use */
#define EDVSCONNREFUSED  (_SIGN 59)  /* connection refused */
#define EDVSCONNRESET    (_SIGN 60)  /* connection reset */
#define EDVSTIMEDOUT     (_SIGN 61)  /* connection timed out */
#define EDVSURG	      (_SIGN 62)  /* urgent data present */
#define EDVSNOURG	      (_SIGN 63)  /* no urgent data present */
#define EDVSNOTCONN      (_SIGN 64)  /* no connection (yet or anymore) */
#define EDVSSHUTDOWN     (_SIGN 65)  /* a write call to a shutdown connection */
#define EDVSNOCONN       (_SIGN 66)  /* no such connection */
#define EDVSAFNOSUPPORT  (_SIGN 67)  /* address family not supported */
#define EDVSPROTONOSUPPORT (_SIGN 68) /* protocol not supported by AF */
#define EDVSPROTOTYPE    (_SIGN 69)  /* Protocol wrong type for socket */
#define EDVSINPROGRESS   (_SIGN 70)  /* Operation now in progress */
#define EDVSADDRNOTAVAIL (_SIGN 71)  /* Can't assign requested address */
#define EDVSALREADY      (_SIGN 72)  /* Connection already in progress */
#define EDVSMSGSIZE      (_SIGN 73)  /* Message too long */
#define EDVSNOTSOCK      (_SIGN 74)  /* Socket operation on non-socket */
#define EDVSNOPROTOOPT   (_SIGN 75)  /* Protocol not available */

/* The following are not POSIX errors, but they can still happen. 
 * All of these are generated by the kernel and relate to message passing.
 */
#define EDVSLOCKED      (_SIGN 101)  /* can't send message due to deadlock */
#define EDVSBADCALL     (_SIGN 102)  /* illegal system call number */
#define EDVSBADSRCDST   (_SIGN 103)  /* bad source or destination process */
#define EDVSCALLDENIED  (_SIGN 104)  /* no permission for system call */
#define EDVSDEADSRCDST  (_SIGN 105)  /* source or destination is not alive */
#define EDVSNOTREADY    (_SIGN 106)  /* source or destination is not ready */
#define EDVSBADREQUEST  (_SIGN 107)  /* destination cannot handle request */
#define EDVSSRCDIED     (_SIGN 108)  /* source just died */
#define EDVSDSTDIED     (_SIGN 109)  /* destination just died */
#define EDVSTRAPDENIED  (_SIGN 110)  /* IPC trap not allowed */
#define EDVSDONTREPLY   (_SIGN 201)  /* pseudo-code: don't send a reply */

/* the following ar MOL error codes */
#define EDVSERRCODE 	(_SIGN 300) 
#define EDVSBADNODEID 	(_SIGN 301)  /* Bad NODE ID */
#define EDVSBADDCID 	(_SIGN 302)  /* Bad DC ID */
#define EDVSDCNOTRUN 	(_SIGN 303)  /* The DC is not running */
#define EDVSBADPROC  	(_SIGN 304)  /* Bad Process Number */
#define EDVSBADPID  	(_SIGN 305)  /* Bad Process ID */
#define EDVSENDPOINT  	(_SIGN 306)  /* Bad Process Endpoint */
#define EDVSNOPROXY 	(_SIGN 307)  /* The IPC proxy is not running */
#define EDVSRMTPROC 	(_SIGN 308)  /* The process is REMOTE */
#define EDVSLCLPROC 	(_SIGN 309)  /* The process is LOCAL */
#define EDVSNOTBIND 	(_SIGN 310)  /* The process has not BINDed */
#define EDVSPROXYRUN 	(_SIGN 311)  /* The IPC proxy is already running */
#define EDVSACKDST 	(_SIGN 312)  /* The IPC proxy sent local process a BAD destination ACK  */
#define EDVSACKSRC 	(_SIGN 313)  /* The IPC proxy sent local process a BAD source ACK  */
#define EDVSACKWAIT 	(_SIGN 314)  /* The IPC proxy sent local process that is not waiting for it  */
#define EDVSNODEBUSY 	(_SIGN 315)  /* NODE is BUSY */
#define EDVSNONODE 	(_SIGN 316)  /* NODE does not exists or is not in list */
#define EDVSDVSBUSY 	(_SIGN 317)  /* The DVS is BUSY - Can't assign new local node ID */
#define EDVSDVSINIT 	(_SIGN 318)  /* The DVS has not been initialized */
#define EDVSNODCNODE 	(_SIGN 319)  /* The NODE is not included into the DC list of nodes */
#define EDVSPROCRUN 	(_SIGN 320)  /* The copy source/destination process is running */
#define EDVSNOMSG 	(_SIGN 321)  /*  No message  - list empty	*/
#define EDVSDCRUN 	(_SIGN 323)  /* The DC is already running */
#define EDVSPROCSTS (_SIGN 324)  	/* Bad process status  */
#define EDVSNODEFREE (_SIGN 325)  /* NODE is FREE */
#define EDVSDCNODE 	(_SIGN 326)  /* The NODE is ALREADY included into the DC list of nodes */
#define EDVSBADPROXY (_SIGN 327)  /* The NODE is ALREADY included into the DC list of nodes */
#define EDVSONCOPY	 (_SIGN 328)  	/* The process is in ONCOPY state  */
#define EDVSENQUEUED	 (_SIGN 329)  	/* The process descriptor is enqueued and cant be used */
#define EDVSOVERRUN	 (_SIGN 330)  	/* An operation couse an overrun of some system resource */
#define EDVSBADOWNER	 (_SIGN 331)  	/* A bind operation try to alloc a slot with other owner */
#define EDVSMIGRATE 	 (_SIGN 332)  	/* The process is migrating */
#define EDVSPROXYFREE 	 (_SIGN 333)  	/* The proxy pair is free  */
#define EDVSGRPLEADER 	 (_SIGN 334)  	/* The process is a child thread, it is not the thread group leader */
#define EDVSPRIVILEGES 	 (_SIGN 335)  	/* The process has no privileges for the call */
#define EDVSBINDTYPE 	 (_SIGN 336)  	/* Bad BIND TYPE */
#define EDVSSLOTUSED 	 (_SIGN 337)  	/* BIND the slot is already used */
#define EDVSBADRANGE 	 (_SIGN 338)  	/* Bad range of a value  */
#define EDVSBADVALUE 	 (_SIGN 339)  	/* Bad value  */
#define EDVSBADDIR 		 (_SIGN 340)  	/* Bad Directory  */
#define EDVSBADFILE		 (_SIGN 341)  	/* Bad File  */
#define EDVSRSCBUSY		 (_SIGN 342)  	/* Resources busy  */
#define EDVSNAMESIZE 	 (_SIGN 343)  	/* Name size too long  */
#define EDVSALLOCMEM	 (_SIGN 344)  	/* Error on allocating memory  */
#define EDVSPROXYID	 	 (_SIGN 345)  	/* Bad PROXY PAIR ID */
#define EDVSREPLPROC 	 (_SIGN 346)  	/* The process is REPLICATED */
#define EDVSALIGN  		 (_SIGN 347)  	/* Addresses not aligned */
#define EDVSWOKENUP	 	(_SIGN 348)  		/* A waiting process has beenb woken up by other process */
#define EDVSBADTRAMP   	(_SIGN 349)  	/* Bad trampoline command */
#define EDVSUSR2USR  	(_SIGN 350)  	/* Signal a waiting process to call a copy trampoline function */
#define EDVSKRN2USR  	(_SIGN 351)  	/* Signal a waiting process to call a copy trampoline function */
#define EDVSUSR2KRN  	(_SIGN 352)  	/* Signal a waiting process to call a copy trampoline function */

/* Errors related to REPLICATION */
#define EDVSPRIMARY		(_SIGN 401)	 /* There is no PRIMARY member */			
#define EDVSNOREPLICA	(_SIGN 402)	 /* There is no Replica members */			

#endif // _COM_DVS_ERRNO_H
















